### ISSUE TITLE
Код не компилируется

### ISSUE THREAD

**Issue by finomen** [qqttrr/Languages#1]
[ 50%] Building CXX object CMakeFiles/parse.dir/parse.cpp.o
/home/finomen/cpp_2014/45/parse.cpp: In function ‘int checkForInt(std::string, int)’:
/home/finomen/cpp_2014/45/parse.cpp:13:31: error: ‘isnumber’ was not declared in this scope
/home/finomen/cpp_2014/45/parse.cpp:17:62: error: ‘isnumber’ was not declared in this scope
/home/finomen/cpp_2014/45/parse.cpp: In function ‘void error_output(int)’:
/home/finomen/cpp_2014/45/parse.cpp:41:11: error: ‘exit’ was not declared in this scope
/home/finomen/cpp_2014/45/parse.cpp: In function ‘void oper(int, std::vector<int>&, char)’:
/home/finomen/cpp_2014/45/parse.cpp:58:23: error: ‘exit’ was not declared in this scope
/home/finomen/cpp_2014/45/parse.cpp:72:23: error: ‘exit’ was not declared in this scope
/home/finomen/cpp_2014/45/parse.cpp: In function ‘int inputcheck(std::string)’:
/home/finomen/cpp_2014/45/parse.cpp:103:17: error: range-based ‘for’ loops are not allowed in C++98 mode
/home/finomen/cpp_2014/45/parse.cpp:117:23: error: ‘isnumber’ was not declared in this scope
/home/finomen/cpp_2014/45/parse.cpp: In function ‘int parse(std::string)’:
/home/finomen/cpp_2014/45/parse.cpp:163:43: error: ‘stoi’ was not declared in this scope
/home/finomen/cpp_2014/45/parse.cpp:170:29: error: ‘isnumber’ was not declared in this scope
/home/finomen/cpp_2014/45/parse.cpp:214:31: error: ‘stoi’ was not declared in this scope
make[2]: *** [CMakeFiles/parse.dir/parse.cpp.o] Error 1
make[1]: *** [CMakeFiles/parse.dir/all] Error 2
make: *** [all] Error 2

**Comment by qqttrr** [comment]
Можно пользоваться стандартом 11 года? Если да, то пофиксил.

**Comment by finomen** [comment]
Можно, если не забывать флаги с системе сборки.

2015-02-23 17:27 GMT+03:00 qqttrr <notifications@github.com>:

> Можно пользоваться стандартом 11 года? Если да, то пофиксил.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qqttrr/Languages/issues/1#issuecomment-75549240>.
>



-- 
Best wishes.
Nikolay Filchenko

**Comment by qqttrr** [comment]
Так проставил же, разве не компилируется?
